name: Build SM64

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download ROM ZIP
        run: |
          mkdir -p baserom
          curl -L -o baserom/rom.zip "https://github.com/gamechanginggambler/Super-Mario-64-Source-Code/releases/download/v1.0.0/Super.Mario.64.zip"

      - name: Inspect ZIP contents
        run: |
          unzip -l baserom/rom.zip

      - name: Unzip ROM
        run: |
          unzip baserom/rom.zip -d baserom
          mv baserom/*.z64 baserom/baserom.us.z64

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3 libpng-dev \
            binutils-mips-linux-gnu gcc-mips-linux-gnu unzip

      - name: Build SM64
        run: |
          make VERSION=us -j$(nproc)

      - name: Upload built ROM
        uses: actions/upload-artifact@v4
        with:
          name: sm64-built-rom
          path: build/us/sm64.us.z64
          
      - name: Upload built ROM
        uses: actions/upload-artifact@v4
        with:
          name: sm64-built-rom
          path: build/us/sm64.us.z64
          
